### ISSUE TITLE
Install error building with Unity 2019.3

### ISSUE THREAD

**Issue by ValeriaColombo** [google/play-instant-unity-plugin#144]
The buil works ok, but build and run throws this error:

```
The APK built successfully.

INFO - Analyzing files...

INFO - Checking device...

INFO - Pushing instant app to device...Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.google.android.instantapps.sdk.cli.RunCommand@49993335): com.google.android.instantapps.sdk.lib.AdbCommandException: ADB process exited with code 1: [install-multiple, -r, -t, --ephemeral, /var/folders/3w/3z34tmvj7pn_ty5gq4xvd21r0000gn/T/temp.apk]
Command output:
adb: failed to finalize session
Failure [-116: Instant app package must use targetSandboxVersion 2]

	at picocli.CommandLine.execute(CommandLine.java:837)
	at picocli.CommandLine.access$700(CommandLine.java:111)
	at picocli.CommandLine$RunAll.handleParseResult(CommandLine.java:1024)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1100)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:1053)
	at com.google.android.instantapps.sdk.cli.Main.aia(Main.java:96)
	at com.google.android.instantapps.sdk.cli.Main.main(Main.java:83)
Caused by: com.google.android.instantapps.sdk.lib.AdbCommandException: ADB process exited with code 1: [install-multiple, -r, -t, --ephemeral, /var/folders/3w/3z34tmvj7pn_ty5gq4xvd21r0000gn/T/temp.apk]
Command output:
adb: failed to finalize session
Failure [-116: Instant app package must use targetSandboxVersion 2]

	at com.google.android.instantapps.sdk.lib.AdbHelper$AdbTarget.adbRead(AdbHelper.java:527)
	at com.google.android.instantapps.sdk.lib.AdbHelper$AdbTarget.installMultiple(AdbHelper.java:277)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.loadAppOPlus(RunHandlerImpl.java:639)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.doRun(RunHandlerImpl.java:456)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.runApks(RunHandlerImpl.java:207)
	at com.google.android.instantapps.sdk.cli.RunCommand.call(RunCommand.java:83)
	at com.google.android.instantapps.sdk.cli.RunCommand.call(RunCommand.java:16)
	at picocli.CommandLine.execute(CommandLine.java:830)
	... 6 more
```

**Comment by thanwah** [comment]
This issue should be fixed as of https://github.com/google/play-instant-unity-plugin/commit/f73453a40295aca5f8bb042c7baf33054a9d6ba2. I will create a new 0.11 release that contains this commit.

**Comment by thanwah** [comment]
Created a new release: https://github.com/google/play-instant-unity-plugin/releases/tag/v0.11

Please let me know if you have any issues. Thanks!
