### ISSUE TITLE
Error Build & Run on Unity 5.6.6f2

### ISSUE THREAD

**Issue by frenb** [google/play-instant-unity-plugin#17]
I tried to build & run an instant app version of my sample project, and I get the following error:

FO - Analyzing files...

INFO - Checking device...

INFO - Pushing instant app to device...

stderr:
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.google.android.instantapps.sdk.cli.RunCommand@28864e92): com.google.android.instantapps.sdk.lib.AdbHelper$AdbCommandException: ADB process exited with code 1: [install-multiple, -r, -t, --ephemeral, /var/folders/js/zwj26yx53j1bw9ywks160ryr00772k/T/temp.apk]
Command output:
adb: failed to finalize session
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: No APK Signature Scheme v2 signature in ephemeral package /data/app/vmdl575792848.tmp/4_temp.apk: No APK Signing Block before ZIP Central Directory]

        at picocli.CommandLine.execute(CommandLine.java:458)
	at picocli.CommandLine.access$300(CommandLine.java:134)
	at picocli.CommandLine$RunAll.handleParseResult(CommandLine.java:566)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:656)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:609)
	at com.google.android.instantapps.sdk.cli.Main.aia(Main.java:61)
	at com.google.android.instantapps.sdk.cli.Main.main(Main.java:53)
Caused by: com.google.android.instantapps.sdk.lib.AdbHelper$AdbCommandException: ADB process exited with code 1: [install-multiple, -r, -t, --ephemeral, /var/folders/js/zwj26yx53j1bw9ywks160ryr00772k/T/temp.apk]
Command output:
adb: failed to finalize session
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: No APK Signature Scheme v2 signature in ephemeral package /data/app/vmdl575792848.tmp/4_temp.apk: No APK Signing Block before ZIP Central Directory]

        at com.google.android.instantapps.sdk.lib.AdbHelper.adbRead(AdbHelper.java:463)
	at com.google.android.instantapps.sdk.lib.AdbHelper.installMultiple(AdbHelper.java:239)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.loadAppOPlus(RunHandlerImpl.java:399)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.doRun(RunHandlerImpl.java:280)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.runInstantApp(RunHandlerImpl.java:107)
	at com.google.android.instantapps.sdk.cli.RunCommand.call(RunCommand.java:40)
	at com.google.android.instantapps.sdk.cli.RunCommand.call(RunCommand.java:13)
	at picocli.CommandLine.execute(CommandLine.java:456)
	... 6 more

exit code: 1

UnityEngine.Debug:LogError(Object)
GooglePlayInstant.Editor.GooglePlayServices.Logger:Log(String, LogLevel) (at Assets/GooglePlayInstant/Editor/GooglePlayServices/Logger.cs:91)
GooglePlayInstant.Editor.GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Assets/GooglePlayInstant/Editor/GooglePlayServices/PlayServicesResolver.cs:37)
GooglePlayInstant.Editor.GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at Assets/GooglePlayInstant/Editor/GooglePlayServices/CommandLineDialog.cs:94)
GooglePlayInstant.Editor.GooglePlayServices.<RunAsync>c__AnonStorey0:<>m__0() (at Assets/GooglePlayInstant/Editor/GooglePlayServices/CommandLine.cs:130)

**Comment by thanwah** [comment]
This issue should have been fixed by PR #13. However, that commit is not currently in the latest 0.6 release. Were you running the plugin at the head version (e.g. git clone the project) or the latest released version?

I'm hoping to get the 0.7 release out very soon, but want it to include PR #15, which is not approved yet.
